import { MentorProfile } from "@/types/mentor";
import { LedgerTransaction } from "@/types/wallet";

export const MOCK_MENTORS: MentorProfile[] = [
  {
    id: "mentor-an-nguyen",
    fullName: "Nguyễn Văn An",
    title: "Tech Lead @ VNG Corporation",
    company: "VNG Corporation",
    yearsOfExperience: 9,
    avatarUrl: "/avatars/avatar-an.png",
    ratingAverage: 4.98,
    reviewCount: 142,
    totalSessions: 218,
    satisfactionRate: 99.1,
    slaResponseTime: "< 15 phút",
    skills: ["Distributed Systems", ".NET 10", "Microservices", "PostgreSQL", "Kafka"],
    bio: "Chuyên sâu Kiến trúc Hệ thống Phân tán, .NET 10, Microservices chịu tải cao. Đã trực tiếp cố vấn và chuẩn bị phỏng vấn cho hơn 200+ kỹ sư đậu vào các tập đoàn công nghệ lớn.",
    isVerified: true,
    isOnline: true,
    nextAvailableSlot: "Trống 19:30 Thứ 6",
    services: [
      {
        id: "svc-an-tier-1",
        tierNumber: 1,
        name: "Review CV & Tối Ưu Portfolio Chuẩn ATS",
        durationMinutes: 45,
        durationLabel: "45 phút",
        priceVnd: 300000,
        category: "QUICK_WIN",
        deliverables: [
          "1-on-1 Deep Dive 45 phút chỉ ra điểm yếu CV trực tiếp.",
          "Notion Checklist sửa từng gạch đầu dòng dự án và số liệu tác động.",
          "Bộ Template Markdown chuẩn Senior Software Engineer.",
        ],
      },
      {
        id: "svc-an-tier-2",
        tierNumber: 2,
        name: "Mock Interview System Design & .NET Microservices",
        durationMinutes: 60,
        durationLabel: "60 phút",
        priceVnd: 450000,
        isFeatured: true,
        category: "FEATURED",
        deliverables: [
          "Mô phỏng phỏng vấn chuẩn FAANG 60 phút thực tế.",
          "Bảng Rubric 10 tiêu chí kỹ thuật chuyên sâu (PDF & Notion chi tiết).",
          "Video ghi hình chất lượng cao & bản vẽ kiến trúc mẫu (Draw.io/Figma).",
          "Cam kết hoàn tiền qua Escrow nếu không đúng thời lượng cam kết.",
        ],
      },
      {
        id: "svc-an-tier-3",
        tierNumber: 3,
        name: "Lộ Trình Software Architect Chuyên Sâu",
        durationMinutes: 240,
        durationLabel: "1 Tháng (4 Buổi)",
        priceVnd: 2000000,
        category: "TRANSFORMATION",
        deliverables: [
          "4 Buổi 1-on-1 trực tiếp giải quyết bài toán thực tế của dự án bạn.",
          "Review PR trên GitHub cá nhân không giới hạn trong 30 ngày.",
          "Async Q&A qua Telegram riêng 24/7 (SLA phản hồi < 2h).",
        ],
      },
    ],
  },
  {
    id: "mentor-duc-tran",
    fullName: "Trần Minh Đức",
    title: "Principal Engineer @ Techcombank",
    company: "Techcombank",
    yearsOfExperience: 11,
    avatarUrl: "/avatars/avatar-duc.png",
    ratingAverage: 4.96,
    reviewCount: 98,
    totalSessions: 160,
    satisfactionRate: 98.8,
    slaResponseTime: "< 30 phút",
    skills: ["High Load Banking", "Kafka", "PostgreSQL", "Event-Driven", "Go"],
    bio: "Hơn 11 năm phát triển Core Banking và thanh toán giao dịch cao. Hướng dẫn thiết kế kiến trúc ngân hàng lõi và tối ưu hóa PostgreSQL cho 10k RPS.",
    isVerified: true,
    isOnline: true,
    nextAvailableSlot: "Trống 20:00 Thứ 7",
    services: [
      {
        id: "svc-duc-tier-1",
        tierNumber: 1,
        name: "Kiểm định High-load Core Banking",
        durationMinutes: 60,
        durationLabel: "60 phút",
        priceVnd: 500000,
        category: "QUICK_WIN",
        deliverables: ["Đánh giá khả năng chịu tải và phân tích bottleneck"],
      },
      {
        id: "svc-duc-tier-2",
        tierNumber: 2,
        name: "Mock Interview FAANG / BigTech",
        durationMinutes: 60,
        durationLabel: "60 phút",
        priceVnd: 600000,
        isFeatured: true,
        category: "FEATURED",
        deliverables: ["Phỏng vấn hệ thống và thuật toán nâng cao"],
      },
      {
        id: "svc-duc-tier-3",
        tierNumber: 3,
        name: "Tư vấn Kiến trúc Event-Driven",
        durationMinutes: 120,
        durationLabel: "2 Buổi",
        priceVnd: 1200000,
        category: "TRANSFORMATION",
        deliverables: ["Thiết kế pipeline xử lý dữ liệu với Apache Kafka"],
      },
    ],
  },
  {
    id: "mentor-nam-le",
    fullName: "Lê Hoàng Nam",
    title: "Senior DevOps Architect",
    company: "AWS Certified Community Hero",
    yearsOfExperience: 8,
    avatarUrl: "/avatars/avatar-nam.png",
    ratingAverage: 5.0,
    reviewCount: 87,
    totalSessions: 120,
    satisfactionRate: 100,
    slaResponseTime: "< 15 phút",
    skills: ["Kubernetes", "AWS EKS", "Terraform", "CI/CD", "Prometheus"],
    bio: "Chuyên gia Cloud Native và tự động hóa hạ tầng Kubernetes, Terraform. Hỗ trợ chuẩn hóa quy trình DevOps, GitOps và tối ưu chi phí Cloud.",
    isVerified: true,
    isOnline: true,
    nextAvailableSlot: "Trống 09:00 Chủ Nhật",
    services: [
      {
        id: "svc-nam-tier-1",
        tierNumber: 1,
        name: "Audit Hạ Tầng Cloud & Chi Phí",
        durationMinutes: 45,
        durationLabel: "45 phút",
        priceVnd: 400000,
        category: "QUICK_WIN",
        deliverables: ["Báo cáo đánh giá bảo mật và tối ưu chi phí AWS"],
      },
      {
        id: "svc-nam-tier-2",
        tierNumber: 2,
        name: "Mock Phỏng Vấn DevOps Quốc Tế",
        durationMinutes: 60,
        durationLabel: "60 phút",
        priceVnd: 550000,
        isFeatured: true,
        category: "FEATURED",
        deliverables: ["Phỏng vấn Kubernetes, K8s Architecture và troubleshooting"],
      },
      {
        id: "svc-nam-tier-3",
        tierNumber: 3,
        name: "Lộ Trình Cloud DevOps K8s",
        durationMinutes: 240,
        durationLabel: "1 Tháng",
        priceVnd: 2200000,
        category: "TRANSFORMATION",
        deliverables: ["Thực hành dựng cụm EKS hoàn chỉnh với GitOps ArgoCD"],
      },
    ],
  },
];

export const MOCK_LEDGER_TRANSACTIONS: LedgerTransaction[] = [
  {
    id: "tx-1",
    txid: "TX-PAY-88210",
    type: "Payout",
    amountVnd: -3000000,
    balanceBeforeVnd: 9200000,
    balanceAfterVnd: 6200000,
    description: "Rút tiền Payout VietQR về MB Bank (0987654321)",
    status: "Completed",
    timestamp: "Hôm nay 11:20",
    auditHash: "sha256:7f83b165...9d81a",
  },
  {
    id: "tx-2",
    txid: "TX-ESC-98115",
    type: "EscrowRelease",
    amountVnd: 450000,
    balanceBeforeVnd: 5750000,
    balanceAfterVnd: 6200000,
    description: "Giải phóng Escrow: Gói Mock Interview - Trần Đình Quân",
    status: "Completed",
    timestamp: "Hôm qua 20:30",
    auditHash: "sha256:4a92e110...2284c",
  },
  {
    id: "tx-3",
    txid: "TX-ESC-98124",
    type: "DisputeHold",
    amountVnd: 450000,
    balanceBeforeVnd: 5750000,
    balanceAfterVnd: 5750000,
    description: "Đóng băng Dispute: Gói Mock Interview - Hoàng Thùy Linh",
    status: "Disputed",
    timestamp: "18/09 20:45",
    auditHash: "sha256:91b2c45e...ff891",
  },
  {
    id: "tx-4",
    txid: "TX-ESC-97992",
    type: "EscrowRelease",
    amountVnd: 300000,
    balanceBeforeVnd: 5450000,
    balanceAfterVnd: 5750000,
    description: "Giải phóng Escrow: Gói Review CV - Đỗ Minh Trí",
    status: "Completed",
    timestamp: "16/09 16:00",
    auditHash: "sha256:12c47a98...bb002",
  },
];
